version: "3"

services:
  app:
    build: ./.docker/
    container_name: transfer_app
    env_file:
        .env
    ports:
      - ${TRANSFER_APP_PORT}:${TRANSFER_APP_PORT}
    volumes:
        - ./:/home/node/transfer-app
    entrypoint: ./.docker/entrypoint.sh
